Env:
  output: "output"
  input: "input"
  port: 12345
Params:
  obfuscate: "{compact: false,controlFlowFlattening: true,controlFlowFlatteningThreshold: 1,numbersToExpressions: true, simplify: true,stringArrayShuffle: true,splitStrings: true, stringArrayThreshold: 1}"